/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#353c48",
        "secondary-fixed-dim": "#a4abbb",
        "primary": "#000000",
        "surface-tint": "#5e5e5e",
        "surface-container-low": "#f3f3f4",
        "on-primary": "#e2e2e2",
        "on-error-container": "#410002",
        "surface-dim": "#dadada",
        "on-secondary-container": "#151c27",
        "secondary": "#585f6c",
        "inverse-on-surface": "#f0f1f1",
        "tertiary-fixed-dim": "#404758",
        "outline-variant": "#c6c6c6",
        "primary-fixed-dim": "#474747",
        "tertiary-container": "#6e7487",
        "on-surface-variant": "#474747",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "on-surface": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed": "#ffffff",
        "tertiary-fixed": "#575e70",
        "tertiary": "#343b4c",
        "surface": "#f9f9f9",
        "outline": "#777777",
        "surface-bright": "#f9f9f9",
        "on-primary-fixed-variant": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "secondary-fixed": "#c0c7d6",
        "primary-container": "#3b3b3b",
        "inverse-primary": "#c6c6c6",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#151c27",
        "on-primary-container": "#ffffff",
        "on-tertiary": "#dce2f7",
        "inverse-surface": "#2f3131",
        "surface-container": "#eeeeee",
        "secondary-container": "#ced4e4",
        "on-error": "#ffffff",
        "surface-container-high": "#e8e8e8",
        "on-tertiary-fixed": "#ffffff",
        "on-tertiary-fixed-variant": "#dce2f7",
        "primary-fixed": "#5e5e5e",
        "on-background": "#1a1c1c",
        "surface-container-highest": "#e2e2e2",
        "background": "#f9f9f9",
        "on-tertiary-container": "#ffffff"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
    },
  },
  plugins: [],
}
